name: rental_booking_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  table_calendar: ^3.2.0
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rental_app.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/rental_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/rental_app.png"
